#
# DCMTKConfig.cmake - DCMTK CMake configuration file for external projects
#

# Basic version information
SET(DCMTK_MAJOR_VERSION 3)
SET(DCMTK_MINOR_VERSION 6)
SET(DCMTK_BUILD_VERSION 1)

# DCMTK build options
SET(DCMTK_WITH_TIFF OFF)
SET(DCMTK_WITH_PNG OFF)
SET(DCMTK_WITH_XML OFF)
SET(DCMTK_WITH_ZLIB OFF)
SET(DCMTK_WITH_OPENSSL OFF)
SET(DCMTK_WITH_SNDFILE OFF)
SET(DCMTK_WITH_ICONV OFF)
SET(DCMTK_WITH_PRIVATE_TAGS OFF)
SET(DCMTK_WITH_THREADS ON)

# DCMTK shared libraries
SET(DCMTK_SHARED_LIBRARIES ON)
SET(DCMTK_SINGLE_SHARED_LIBRARY ON)

# DCMTK additional options
SET(DCMTK_OVERWRITE_WIN32_COMPILER_FLAGS ON)
SET(DCMTK_WIDE_CHAR_FILE_IO_FUNCTIONS OFF)
SET(DCMTK_WIDE_CHAR_MAIN_FUNCTION OFF)
